backend:
  name: git-gateway
  branch: master

  media_folder: "static/uploads"
  public_folder: "uploads"

  collections:
    - name: "coding"
      label: "coding"
      folder: "content/blog"
      create: true
      slug: "{{year}}-{{slug}}"
      fields:
        - {lable: "Title", name: "title", widget: "string"}
        - {lable: "Publish Date", name: "date", widget: "date"}
        - {lable: "Tags", name: "tags", widget: "list", required: true}
        - {lable: "Author", name: author, widget: hidden, default: Lenord}
        - {lable: "Header Image", name: "image", widget: "image", required: false}
        - {lable: "Commenting", name: "comments", widget: "boolean", default: true}
        - {lable: "Type", name: type, widget: hidden, default: "post"}
        - {lable: "Body", name: "body", widget: "markdown"}